//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlughafenDBEntities : DbContext
    {
        public FlughafenDBEntities()
            : base("name=FlughafenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flug> Flug { get; set; }
        public virtual DbSet<Flughafen> Flughafen { get; set; }
        public virtual DbSet<Fluglinie> Fluglinie { get; set; }
        public virtual DbSet<Flugzeug> Flugzeug { get; set; }
    }
}
