//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flug
    {
        public int Flug_ID { get; set; }
        public string Flugnr { get; set; }
        public short Von { get; set; }
        public short Nach { get; set; }
        public System.DateTime Abflug { get; set; }
        public System.DateTime Ankunft { get; set; }
        public int Fluglinie_ID { get; set; }
        public int Flugzeug_ID { get; set; }
        public Nullable<int> Test { get; set; }
    
        public virtual Flughafen Flughafen { get; set; }
        public virtual Flughafen Flughafen1 { get; set; }
        public virtual Fluglinie Fluglinie { get; set; }
        public virtual Flugzeug Flugzeug { get; set; }
    }
}
