//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fluglinie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fluglinie()
        {
            this.Flug = new HashSet<Flug>();
        }
    
        public int Fluglinie_ID { get; set; }
        public string IATA { get; set; }
        public string Firmenname { get; set; }
        public short Heimat_Flughafen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flug> Flug { get; set; }
        public virtual Flughafen Flughafen { get; set; }
    }
}
